### ISSUE TITLE
How to make animated icon?

### ISSUE THREAD

**Issue by dheerajbred** [yako-dev/flutter-status-alert#1]
This is not an issue. Just wanted to know how you made this animated tick icon
![image](https://raw.githubusercontent.com/yako-dev/flutter-status-alert/master/assets/apple_podcasts_subscribed_animation.gif)

**Comment by yadaniyil** [comment]
This animation is done with Flare. You can check the commented code in [the example](https://github.com/yako-dev/flutter-status-alert/blob/master/example/lib/screens/status_alert_screen.dart).
