### ISSUE TITLE
type 'MaterialColor' is not a subtype of type 'bool

### ISSUE THREAD

**Issue by faridistiqlal** [yako-dev/flutter-status-alert#6]
in [April 1, 2020] you Fixed issue "Type 'Color' is not a subtype of type 'bool'"
but error when adding backgroundColor, Help me

Thanks

**Comment by jefflyne** [comment]
in status_alert_base_widget.dart

change:
 `decoration: BoxDecoration(
              color: widget.backgroundColor ??
                      Theme.of(context).brightness == Brightness.dark
                  ? darkBackground
                  : lightBackground,`
to:
 `decoration: BoxDecoration(
              color: widget.backgroundColor,`


you will have to clone the repo and change the package in pubspec.yaml to a local package

example:
  status_alert:
    path: ./packages/flutter-status-alert

**Comment by yadaniyil** [comment]
@jefflyne @faridistiqlal, sorry for delay.
Fixed in the version `status_alert: ^0.1.3`
