### ISSUE TITLE
Type 'Color' is not a subtype of type 'bool' (Color Icon)

### ISSUE THREAD

**Issue by faridistiqlal** [yako-dev/flutter-status-alert#7]
Background color fix in version 0.13.

My question :
configuration : IconConfiguration(
Icon : icons.done, (success)
(Add) color: Colors.white (error colors not type bool)
)
How to change color icon?
Thanks

**Comment by TJMusiitwa** [comment]
I agree this still needs to be fixed in the latest version pre-null-safety

**Comment by RusKryzhanovskiy** [comment]
@faridistiqlal, @TJMusiitwa sorry for the delay.

We have no plans to support older versions. 
You can use the latest version. 
The bug has been fixed there.
