### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies

### ISSUE THREAD

**Issue by anushkapubudu** [yako-dev/flutter-status-alert#9]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:status_alert
 - package:flare_flutter
 - package:flare_dart

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 47s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by yadaniyil** [comment]
Hey @anushkapubudu  Please check a new 1.0.0 version and let me know if there any issues, thanks
